### ISSUE TITLE
touch: Failed to get two point touch detection

### ISSUE THREAD

**Issue by mcuw** [Xinyuan-LilyGO/T-Display-S3-Long#20]
Hi,

it looks like the two point touch detection is not working ...

```
uint16_t pointX = AXS_GET_POINT_X(buff, 1);
uint16_t pointY = AXS_GET_POINT_Y(buff, 1);
```

Both values are always zero even when the point num is 2:

```
uint8_t num = AXS_GET_POINT_NUM(buff)
```

num == 2

**Comment by lewisxhe** [comment]
I need to consult with the supplier, I will update if there is any new progress

**Comment by lewisxhe** [comment]
Because the read data size is single point data, just change it to read two point data size.

**Comment by vanvuongngo** [comment]
Thanks a lot for the quick fix. Good catch and works fine. You can close this issue.

**Comment by mcuw** [comment]
Thanks a lot for your quick fix. Good catch and works fine.
