### ISSUE TITLE
Data Sheet vs board error

### ISSUE THREAD

**Issue by rhcp4life** [Xinyuan-LilyGO/T-Display-S3-Long#23]
The Header pins on the back of the board are listed as 5v,5v,Bat,Bat,3,4,5,6,7,8,9,48,49,GND,GND. But on the data sheet there is a blank pin separated between Bat and 3. and it only goes from 3-8, then 48,49. 
![image](https://github.com/Xinyuan-LilyGO/T-Display-S3-Long/assets/6364405/fe2664cd-4f26-489f-9c93-adecbcc3171c)
![image](https://github.com/Xinyuan-LilyGO/T-Display-S3-Long/assets/6364405/bb5eb04f-cae5-4484-90a7-34a0f670a62c)

**Comment by rhcp4life** [comment]
It Appears the Board printout is correct and the datasheet has an error.

**Comment by lewisxhe** [comment]
Thanks, updated
