### ISSUE TITLE
Need instructions for converting images to lvgl C files.

### ISSUE THREAD

**Issue by tavdog** [Xinyuan-LilyGO/T-Display-S3-Long#28]
I spent hours figuring this out with the original TFT (non long) version and now I'm having to do the same with this board.  Can you please provide some steps and configuration on how to convert images to a useable lvgl / c array for use with this board ? I've tried many different settings and options https://lvgl.io/tools/imageconverter but it doesn't not work. Image appears garbled.

**Comment by fundix** [comment]
Try SquareLine studio for gui and images generation.
