### ISSUE TITLE
Consult screen model

### ISSUE THREAD

**Issue by TopgunZh** [Xinyuan-LilyGO/T-Display-S3-Long#35]
I would like to know the model of the touch screen and where to buy it. Your screen is very good and I want to use it in my DIY works.

**Comment by fundix** [comment]
> I would like to know the model of the touch screen and where to buy it. Your screen is very good and I want to use it in my DIY works.

https://tailorpixels.com/product/3-4-inch-touch-lcd-in-cell-spi-mipi-qspi-180x64/

**Comment by TopgunZh** [comment]
Thanks
