### ISSUE TITLE
How to use both Qwiic ports?

### ISSUE THREAD

**Issue by d3mac123** [Xinyuan-LilyGO/T-Display-S3-Long#9]
Hi, 

How to use both I2C ports (plus the touch part)? I can connect to one port using the Wire1 option (see below), but I am not sure on how to also enable the second port (pins 18 and 15?).

```
void setup() {
    Serial.begin(115200);
    Serial.println("sta\n");

    pinMode(TOUCH_RES, OUTPUT);
    digitalWrite(TOUCH_RES, HIGH);delay(2);
    digitalWrite(TOUCH_RES, LOW);delay(10);
    digitalWrite(TOUCH_RES, HIGH);delay(2);

    Wire.begin(TOUCH_IICSDA, TOUCH_IICSCL);
    Wire1.begin(43,44);
    uint8_t TMP102_address = 0x48;
    sensor0.begin(TMP102_address , Wire1);

    axs15231_init();  //If you use touch, you must initialize the screen first

    Serial.println("end\n");
}
```

**Comment by lewisxhe** [comment]
For the touch group of I2C, you only need to initialize the touch, and Qwiic can go up directly.

**Comment by d3mac123** [comment]
Not sure I understood your reply: how to enable my second port? My sensors need to have the Wire command enabling the proper pins - for the first Qwiic connector, I use Wire1.begin(43,44));

**Comment by lewisxhe** [comment]
I added an example, hope it helps you
